In [8]:
import os
import glob
import pandas as pd
os.getcwd()
pd.options.display.max_columns = 65
pd.options.display.max_rows = 13000000
print(pd.options.display.max_rows)

13000000

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
#combine all files in the list
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ], ignore_index = True)
#combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])

C:\Users\yz339c\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3185: DtypeWarning: Columns (43) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):

In [5]:
combined_csv.head()
combined_csv.shape

(12771253, 60)

In [6]:
#export to csv
combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

In [9]:
combined_csv.to_pickle('OTP_11.17.19.pkl')  #to save the dataframe, combined csv to OTP_11.17.19.pkl
#OTP - ON time performance downloaded on  11.17.19

'''
#To load pickle data
df = pd.read_pickle('OTP_11.17.19.pkl')
# to load 1OTP_11.17.19.pkl back to the dataframe df
'''

"\n#To load pickle data\ndf = pd.read_pickle('OTP_11.17.19.pkl')\n# to load 1OTP_11.17.19.pkl back to the dataframe df\n"

In [12]:
'''
import feather
%time feather.write_dataframe(combined_csv, 'feather.OTP_11.17.19')
####
pip install fastparquet
from fastparquet import write 
write('outfile.parq', df)
OR
df.to_parquet('df.parquet.gzip', compression='gzip')
pd.read_parquet('df.parquet.gzip')

OR
import pyarrow as pa
import pyarrow.parquet as pq

df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
table = pa.Table.from_pandas(df, preserve_index=True)
pq.write_table(table, 'output.parquet')
'''

"\nimport feather\n%time feather.write_dataframe(combined_csv, 'feather.OTP_11.17.19')\n####\npip install fastparquet\nfrom fastparquet import write \nwrite('outfile.parq', df)\nOR\ndf.to_parquet('df.parquet.gzip', compression='gzip')\npd.read_parquet('df.parquet.gzip')\n\nOR\nimport pyarrow as pa\nimport pyarrow.parquet as pq\n\ndf = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})\ntable = pa.Table.from_pandas(df, preserve_index=True)\npq.write_table(table, 'output.parquet')\n"

In [13]:
combined_csv.tail()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,Unnamed: 59
12771248,2018,3,9,7,5,2018-09-07,UA,19977,UA,2298,13198,1319801,33198,MCI,"Kansas City, MO",MO,Missouri,13930,1393006,30977,ORD,"Chicago, IL",IL,Illinois,800,758.0,-2.0,0.0,0.0,-1.0,0800-0859,10.0,808.0,905.0,12.0,931,917.0,-14.0,0.0,0.0,-1.0,0900-0959,0.0,NaN,0.0,91.0,79.0,57.0,1.0,403.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12771249,2018,3,9,7,5,2018-09-07,UA,19977,UA,2297,11292,1129202,30325,DEN,"Denver, CO",CO,Colorado,10140,1014005,30140,ABQ,"Albuquerque, NM",NM,New Mexico,1525,1518.0,-7.0,0.0,0.0,-1.0,1500-1559,14.0,1532.0,1630.0,3.0,1646,1633.0,-13.0,0.0,0.0,-1.0,1600-1659,0.0,NaN,0.0,81.0,75.0,58.0,1.0,349.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12771250,2018,3,9,7,5,2018-09-07,UA,19977,UA,2296,10140,1014005,30140,ABQ,"Albuquerque, NM",NM,New Mexico,11292,1129202,30325,DEN,"Denver, CO",CO,Colorado,1755,1753.0,-2.0,0.0,0.0,-1.0,1700-1759,12.0,1805.0,1904.0,7.0,1921,1911.0,-10.0,0.0,0.0,-1.0,1900-1959,0.0,NaN,0.0,86.0,78.0,59.0,1.0,349.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12771251,2018,3,9,7,5,2018-09-07,UA,19977,UA,2295,12266,1226603,31453,IAH,"Houston, TX",TX,Texas,13198,1319801,33198,MCI,"Kansas City, MO",MO,Missouri,2140,2157.0,17.0,17.0,1.0,1.0,2100-2159,13.0,2210.0,2335.0,5.0,2333,2340.0,7.0,7.0,0.0,0.0,2300-2359,0.0,NaN,0.0,113.0,103.0,85.0,1.0,643.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12771252,2018,3,9,7,5,2018-09-07,UA,19977,UA,2294,10721,1072102,30721,BOS,"Boston, MA",MA,Massachusetts,14771,1477104,32457,SFO,"San Francisco, CA",CA,California,915,913.0,-2.0,0.0,0.0,-1.0,0900-0959,17.0,930.0,1238.0,4.0,1245,1242.0,-3.0,0.0,0.0,-1.0,1200-1259,0.0,NaN,0.0,390.0,389.0,368.0,1.0,2704.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN